<?php

declare(strict_types=1);

namespace JMac\Testing;

use JMac\Testing\Engine\MethodExpectation;
use JMac\Testing\Engine\ReceivedAssertion;

/**
 * The six control verbs every double generated by `TestDouble::for()`
 * actually has at runtime — `Engine\DoubleControlMethods` both uses this as
 * a trait and `implements` it directly, so it's a real, checkable fact, not
 * a docblock-only fiction.
 *
 * Exists for static analysis, not a new capability: a trait can't appear in
 * a PHPStan/Psalm intersection type, only an interface can, and
 * `TestDouble::for()`'s return type needs to express "whatever type you
 * asked for, plus these six methods."
 */
interface TestDoubleInterface
{
    public function expects(string $method): MethodExpectation;

    public function allows(string $method): MethodExpectation;

    public function strict(): static;

    public function passthru(?object $realInstance = null): static;

    public function received(string $method): ReceivedAssertion;

    public function verify(): void;
}
