<?php

declare(strict_types=1);

namespace JMac\Testing;

use JMac\Testing\Engine\MethodExpectation;
use JMac\Testing\Engine\ReceivedAssertion;

/**
 * The six control verbs every double generated by `TestDouble::for()`
 * actually has at runtime (see `Engine\DoubleControlMethods`, which every
 * generated class both uses as a trait and — specifically so this interface
 * is a real, checkable fact rather than a docblock-only fiction —
 * `implements` directly; see `ClassGenerator::buildSource()`).
 *
 * This interface exists for static analysis, not for a new capability: a
 * trait can't appear in a PHPStan/Psalm intersection type, only an
 * interface can, and `TestDouble::for()`'s return type needs to express
 * "whatever type you asked for, plus these six methods." See its own
 * docblock for the `@template`/`@return` pairing that uses this.
 */
interface TestDoubleInterface
{
    public function expects(string $method): MethodExpectation;

    public function allows(string $method): MethodExpectation;

    public function strict(): static;

    public function passthru(?object $realInstance = null): static;

    public function received(string $method): ReceivedAssertion;

    public function verify(): void;
}
